# Generated by Django 5.1.1 on 2026-02-04 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_alter_tutorsession_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorsession',
            name='last_question',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tutorsession',
            name='tutor_questions_asked',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tutorsession',
            name='tutor_questions_correct',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tutorsession',
            name='status',
            field=models.CharField(choices=[('IDLE', 'Idle'), ('TEACHING', 'Teaching'), ('AWAITING_ANSWER', 'Awaiting Answer'), ('AWAITING_SWITCH_CONFIRMATION', 'Awaiting Switch Confirmation'), ('AWAITING_PLAN_APPROVAL', 'Awaiting Plan Approval')], default='IDLE', max_length=50),
        ),
    ]
